stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
      - data/MachineLearningRating_v3.txt
      - src/data_loader.py
      - src/prepare_data.py
    outs:
      - data/processed/insurance_cleaned.csv

  validate:
    cmd: python src/validate_data.py
    deps:
      - data/processed/insurance_cleaned.csv
      - src/validate_data.py
